filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, data/*]
checks:
    php:
        return_doc_comment_if_not_inferrable: true
        param_doc_comment_if_not_inferrable: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        avoid_perl_style_comments: true
tools:
    external_code_coverage:
        timeout: 1000 # travis.org may have long queues to work until coverage is sent
        runs: 2
    php_code_sniffer:
      config:
        standard: "PSR2" # Other Values: PSR2, PEAR, Zend, WordPress, Drupal, TYPO3CMS
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            other:
                after_type_cast: false
