filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, data/*]
checks:
    php:
        return_doc_comment_if_not_inferrable: true
        param_doc_comment_if_not_inferrable: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        avoid_perl_style_comments: true
tools:
    external_code_coverage:
        timeout: 1000 # travis.org may have long queues to work until coverage is sent
        runs: 3 # wait for results from all 4 travis jobs as hhvm reports different coverage stats
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            within:
                brackets: true
            other:
                after_type_cast: false

