language: php
php:
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true

before_script:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit $PHPUNIT_FLAGS

after_script:
  - |
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
