sudo: false
language: php
php:
  - 5.6
  - 7.0
  - hhvm
matrix:
  fast_finish: true

before_script:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - |
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
