language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true

before_script:
  - composer selfupdate && composer --version
  - composer require satooshi/php-coveralls --dev --prefer-dist
  - composer update --dev --prefer-dist

script:
  - phpunit --coverage-clover=clover.xml

after_script:
  - php vendor/bin/coveralls

cache:
  directories:
    - vendor
