language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true

before_script:
  - composer selfupdate && composer --version
  - composer update --dev --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

cache:
  directories:
    - vendor
