<?php
/**
 * DumpAstCommand.php
 *
 * MIT LICENSE
 *
 * LICENSE: This source file is subject to the MIT license.
 * A copy of the licenses text was distributed alongside this
 * file (usually the repository or package root). The text can also
 * be obtained through one of the following sources:
 * * http://opensource.org/licenses/MIT
 * * https://github.com/suralc/pvra/blob/master/LICENSE
 *
 * @author     suralc <thesurwaveing@gmail.com>
 * @license    http://opensource.org/licenses/MIT  MIT
 */
namespace Pvra\Console\Commands;


use PhpParser\Lexer\Emulative;
use PhpParser\NodeTraverser;
use PhpParser\NodeVisitor\NameResolver;
use PhpParser\Parser;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class DumpAstCommand
 *
 * @package Pvra\Console\Commands
 */
class DumpAstCommand extends PvraBaseCommand
{
    /**
     * @inheritdoc
     */
    protected function configure()
    {
        $this
            ->setName('debug:dumpAst')
            ->setDescription('Dumps the AST of a file generated by PHP-Parser to the console');

        parent::configure();

        $this
            ->addOption('file', 'f', InputOption::VALUE_REQUIRED, 'File to dump');
    }

    /**
     * @inheritdoc
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $file = $input->getOption('file');

        if (!is_file($file) || !is_readable($file)) {
            $output->writeln(sprintf('<error>"%s" is not a valid file.</error>', $file));
            return 0x2;
        }

        $parser = new Parser(new Emulative);

        $stmts = $parser->parse(file_get_contents($file));

        if ($input->getOption('preventNameExpansions') !== true) {
            $traverser = new NodeTraverser();
            $traverser->addVisitor(new NameResolver());
            $stmts = $traverser->traverse($stmts);
        }

        if ($input->getOption('extensive')) {
            var_dump($stmts);
        } else {
            print_r($stmts);
        }
    }
}
